const ADD_MOVIES = 'ADD_MOVIES'
const SET_FILTER = 'SET_FILTER'
const SEARCH_MOVIE = 'SEARCH_MOVIE'
const REMOVE_MOVIES = 'REMOVE_MOVIES'

export {
	ADD_MOVIES,
	SET_FILTER,
	SEARCH_MOVIE,
	REMOVE_MOVIES
}